In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [63]:
df1=pd.read_csv("match_data.csv")
df2=pd.read_csv("match_info_data.csv")

In [64]:
df1.head(3)

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353

In [65]:
df1.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'cricsheet_id'],
      dtype='object')

In [66]:
df2.head(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1370353,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370352,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal
2,1370351,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney

In [67]:
df2.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [68]:
import warnings
warnings.filterwarnings("ignore")

In [69]:
df=pd.merge(df1,df2,left_on="match_id",right_on="id")

In [70]:
df.head(3)

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue_y,umpire1,umpire2,umpire3
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan

In [71]:
df.columns

Index(['match_id', 'season_x', 'start_date', 'venue_x', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'cricsheet_id', 'id', 'season_y', 'city',
       'date', 'team1', 'team2', 'toss_winner', 'toss_decision', 'result',
       'dl_applied', 'winner', 'win_by_runs', 'win_by_wickets',
       'player_of_match', 'venue_y', 'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [72]:
df.dtypes

match_id                    int64
season_x                   object
start_date                 object
venue_x                    object
innings                     int64
ball                      float64
batting_team               object
bowling_team               object
striker                    object
non_striker                object
bowler                     object
runs_off_bat                int64
extras                      int64
wides                     float64
noballs                   float64
byes                      float64
legbyes                   float64
penalty                   float64
wicket_type                object
player_dismissed           object
other_wicket_type         float64
other_player_dismissed    float64
cricsheet_id                int64
id                          int64
season_y                   object
city                       object
date                       object
team1                      object
team2                      object
toss_winner                object
toss_decision              object
result                     object
dl_applied                  int64
winner                     object
win_by_runs                 int64
win_by_wickets              int64
player_of_match            object
venue_y                    object
umpire1                    object
umpire2                    object
umpire3                    object
dtype: object

In [73]:
df.shape

(243817, 41)

In [74]:
df.isnull().sum().sort_values(ascending=False).head(15)

other_player_dismissed    243817
other_wicket_type         243817
penalty                   243815
byes                      243189
noballs                   242799
legbyes                   240039
wides                     236165
wicket_type               231750
player_dismissed          231750
city                       12397
winner                      4124
umpire3                      689
player_of_match              490
striker                        0
venue_x                        0
dtype: int64

In [75]:
df["penalty"].unique()

array([nan,  5.])

In [76]:
df["penalty"].fillna(0,inplace=True)

In [77]:
df["byes"].unique()

array([nan,  1.,  4.,  2.,  3.])

In [78]:
df["byes"].fillna(0,inplace=True)

In [79]:
print("For Noballs : ",df["noballs"].unique())
print("For Legbyee : ",df["legbyes"].unique())
print("For Wides : ",df["wides"].unique())

For Noballs :  [nan  1.  2.  5.  3.]
For Legbyee :  [nan  1.  4.  2.  3.  5.]
For Wides :  [nan  1.  2.  5.  3.  4.]

In [80]:
df["noballs"].fillna(0,inplace=True)
df["legbyes"].fillna(0,inplace=True)
df["wides"].fillna(0,inplace=True)

In [81]:
df.isnull().sum().sort_values(ascending=False).head(15)

other_player_dismissed    243817
other_wicket_type         243817
wicket_type               231750
player_dismissed          231750
city                       12397
winner                      4124
umpire3                      689
player_of_match              490
match_id                       0
striker                        0
bowling_team                   0
batting_team                   0
ball                           0
innings                        0
venue_x                        0
dtype: int64

In [82]:
df.drop(columns=["other_player_dismissed","other_wicket_type"],inplace=True)

In [86]:
df["player_dismissed"].fillna("NO One",inplace=True)

In [89]:
df["wicket_type"].unique()

array([nan, 'stumped', 'caught', 'lbw', 'caught and bowled',
       'retired out', 'bowled', 'run out', 'retired hurt', 'hit wicket',
       'obstructing the field'], dtype=object)

In [90]:
df["wicket_type"].fillna("No_Wicket",inplace=True)

In [92]:
df.isnull().sum().sort_values(ascending=False).head(5)

city               12397
winner              4124
umpire3              689
player_of_match      490
match_id               0
dtype: int64

In [95]:
df.head(20)

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue_y,umpire1,umpire2,umpire3
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
3,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
4,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
5,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.6,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
6,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,1.1,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
7,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,1.2,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
8,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,1.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
9,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,1.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
10,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,1.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
11,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,1.6,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
12,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,2.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
13,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,2.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
14,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,2.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
15,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,2.4,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
16,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,2.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
17,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,2.6,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
18,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,3.1,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
19,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,3.2,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan

In [94]:
df["city"].unique()

array(['Ahmedabad', 'Chennai', 'Mumbai', 'Bengaluru', 'Delhi', 'Kolkata',
       'Dharamsala', 'Hyderabad', 'Lucknow', 'Jaipur', 'Chandigarh',
       'Guwahati', 'Navi Mumbai', 'Pune', 'Dubai', 'Sharjah', 'Abu Dhabi',
       nan, 'Visakhapatnam', 'Indore', 'Bangalore', 'Kanpur', 'Rajkot',
       'Raipur', 'Ranchi', 'Cuttack', 'Kochi', 'Nagpur', 'Johannesburg',
       'Centurion', 'Durban', 'Bloemfontein', 'Port Elizabeth',
       'Kimberley', 'East London', 'Cape Town'], dtype=object)